### PR TITLE
Use Djula style tags

### PR DESCRIPTION
**Pull request by ahungry**
This may be an undesired change, but in finding this library, I felt it would be easier to modify the tag parser to use more of a Djula/Twig aligned syntax (Python/PHP templating libraries) rather than adapt my tools to use this rather unique tag style.

If you'd like to merge, feel free to remove the 'modified blabla' references, those are so no one incorrectly clones my fork and assumes it is the same, or backwards compatible with your original implementation.

Thanks for your work on this!

### CODE REVIEW

**Comment by rla** [comment]
Thank you for the pull request! However, changing the instruction delimiters is a too big incompatibility change and as SWI packs do not support any kind of versioning, I cannot merge this in the current form. Not sure about others but I have over 10 projects with 10k locs of template code that would be incompatible with the new version. I see these solutions:

1. Support arbitrary begin/end tags. I'm not exactly sure how to implement this for languages that use inconsistent tags, like Twig uses `{%` for blocks but `{{` for includes.

2. Fork the library. Rename it to djula-template and change the maintainer/author while also retaining the original license and copyright. Modules should be renamed to use dt_ prefix. I would NOT maintain this library.

3. Provide djula front-end module. The front-end would be configurable through the `frontend` option. By default it would use the current front-end which would retain backwards compatibility. The new frontend needs a separate set of tests that cover the frontend part mostly.

As most of the changes are in the frontend then (3) looks doable. Let me know what you think of it.

**Comment by ahungry** [comment]
I like the idea of #3, please find an updated pull request that retains 100% backwards compatabilty, and introduces the alternate syntax via one of the option settings (frontend: semblance), which has the same test coverage as the default syntax tokenizer in all test files (parse/render/tokenizer/block).

**Comment by rla** [comment]
This seems to be good. I would like these additional changes:

 * Original syntax as `simple` (currently `st_tokens`).
 * Rename module `st_tokens` to `st_simple_tokens`. Tokenization predicate to `st_simple_tokens`.
 * Throw error when the asked frontend is neither `simple` or `semblance` + test.
 * Remove `init_fe`, should be unnecessary.
 * Remove dynamic `use_module`. Add `st_tokens` that checks options and tokenizes the text.
 * Refactor out common parts of both tokenizers.

**Comment by ahungry** [comment]
@rla updated as requested (I am pretty sure I hit all the items you mentioned, hopefully to your liking)

**Comment by rla** [comment]
I have merged this into master. I'm going over the code and documentation and then create a release.

**Comment by rla** [comment]
I did some more aggressive tokenizer refactoring and some cleanups. Released version 1.1.0.

**Pull request merged**
