### PR TITLE
Assign `false` to `Value` instead of throwing a no_entry error.

### PR DESCRIPTION
**Pull request by sandogeorge**
This is useful in situations where the user may want to include a block in the template based on the existence of a variable. For example:

```html
{% if page_header %}
<h2>{{page_header}}</h2>
{% end %}
```

### CODE REVIEW

**Comment by rla** [comment]
Thank you for the pull request. As this changes the code behavior I would like to see this be configurable with the old behavior as the default and covered by tests. `st_eval` predicates will need to have `Options` passed through. Documentation has to be updated.

The option name should be `undefined` with values either `error` (default) or `false` (enables the behavior described in this PR).

The LICENSE file has be updated. Add your real name to the list of copyright holders.

**Comment by sandogeorge** [comment]
Thanks for the clear instructions on what needed to be done. The latest commit has addressed your concerns. Let me know if there is anything else I can do.

**Comment by rla** [comment]
I did some additional changes in code and I have released 1.2.0.

**Comment by sandogeorge** [comment]
Thank you!

**Pull request merged**
